version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/certs
    depends_on:
      - video-streaming1
      - video-streaming2
      - video-streaming3

  video-streaming1:
    build: ./video-streaming
    environment:
      - PORT=3001
    ports:
      - "3001:3001"

  video-streaming2:
    build: ./video-streaming
    environment:
      - PORT=3002
    ports:
      - "3002:3002"

  video-streaming3:
    build: ./video-streaming
    environment:
      - PORT=3003
    ports:
      - "3003:3003"
